services:
  db:
    container_name: finance_db
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sercret
      POSTGRES_DB: finance_db
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/